Fix runner exception due to stats calc in virtualenv.
Fixes exception. This module is not inside runner virtualenv.
virtualenv is not needed in first place now since all those deps
in base-image. so simplify.

Traceback (most recent call last):
  File "/src/experiment/runner.py", line 368, in do_sync
    self.record_stats()
  File "/src/experiment/runner.py", line 380, in record_stats
    fuzzer_module = get_fuzzer_module(self.fuzzer)
  File "/src/experiment/runner.py", line 465, in get_fuzzer_module
    fuzzer_module = importlib.import_module(fuzzer_module_name)
  File "/src/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/fuzzers/afl_fast_agg/fuzzer.py", line 23, in <module>
    from fuzzers.afl import fuzzer as afl_fuzzer
  File "/src/fuzzers/afl/fuzzer.py", line 21, in <module>
    from fuzzers import utils
  File "/src/fuzzers/utils.py", line 24, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'